### ISSUE TITLE
"Learn how to say no politely" maybe under Politics section?

### ISSUE THREAD

**Issue by anenadic** [philippbayer/Things-a-scientist-is-suppposed-to-know#1]
This about how to learn to decline things politely and how to choose what one wants/should get involved in (not just from a career perspective but for self-preservation). I definitely need this skill :-).

P.S. Love this repo! I am going to forward to my husband, also an academic who does not know when to say 'no'.

**Comment by philippbayer** [comment]
Good idea!! I have added that 

Thanks for the P.S. :)
